FROM kommunitasorg/kommunitas:develop

# Install dependencies
COPY requirements-dev.txt /kommunitas/

RUN pip install numpy --user --no-cache-dir \
  && pip install -r requirements-dev.txt --user --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
